### ISSUE TITLE
Generating graphs of state machines from DSL

### ISSUE THREAD

**Issue by xkr47** [eugene-babichenko/rust-fsm#3]
Hi,

I made a quick hack that produces state machine graph from state machines defined using the DSL. It currently produces [graphviz](https://graphviz.org/) .dot files which can be rendered to images in a plethora of formats - png, svg, ps, pdf etc. As an example, for the example in rust-fsm's README.md, it produces a `CircuitBreaker.dot` file:
```dot
digraph "graph" {
  rankdir="LR";
  SM_init [label="", shape=point];
  SM_init -> "Closed";
  "Closed" -> "Open" [label="Unsuccessful [SetupTimer]" minlen=2];
  "Open" -> "HalfOpen" [label="TimerTriggered" minlen=2];
  "HalfOpen" -> "Closed" [label="Successful" minlen=2];
  "HalfOpen" -> "Open" [label="Unsuccessful [SetupTimer]" minlen=2];
}
```
.. which using the `dot -Tpng CircuitBreaker.dot > CircuitBreaker.png` command from the graphviz package generates the following image:

![CircuitBreaker](https://user-images.githubusercontent.com/1488474/100496884-77b67600-3160-11eb-950f-f74533b02b3c.png)

The code is available [here](https://github.com/xkr47/rust-fsm-graph); I copy-pasted the `parser.rs` module from your project because it was not exported.

I post this issue hoping to receive feedback from you on this; would any of the following options be interesting to you?

1. Agree to export the DSL parser from the rust-fsm-dsl crate so my tool could use it directly instead of copypasting it?
2. Mention the project in your README for your users' benefit
3. Integrate the code directly into rust-fsm

The tool could be further improved for example perhaps by e.g. seamlessly integrating it to the `cargo doc` or similar so the graphs could be part of the crate's documentation if wanted.

**Comment by eugene-babichenko** [comment]
Hi,

This is a great idea which I was thinking about it about a year ago or so but didn't do that because it wasn't particularly useful for me.

Out of these three options I am leaning towards adding the code generation into `rust-fsm-dsl` behind a feature gate (let's say, `generate-dot`) which will populate an optional associated constant `GRAPHVIZ` in `StateMachine`. By 'optional' I mean that it can be either an `Option<&'static str>` or be feature-gated as well. The latter makes more sense to me.

To sum up this part: if you are ok with contributing your code to this repo, please add a feature-gated constant to `StateMachine` and generate it's contents in `rust-fsm-dsl` during macro expansion.

Regarding `cargo doc`: this is a tricky part. AFAIK `cargo doc` does not have any support for DOT, so you will have to generate an image or some sort of ASCII graphics. I'd rather leave it up to the user, or postpone the implementation of such feature and make it in a separate pull request.

Lastly, a couple remarks on the code you wrote. This is a nice piece overall, but it needs to be configurable to be used inside of the library. The DOT attributes you are using look mostly sane to me, but they need to be documented and the users should be able to change them if they want to. This could be done by specifying these settings from the DSL for example. Also note, that integrating this into the library will make your life a bit easier, because you can use [the internal `Transition` structure](https://github.com/eugene-babichenko/rust-fsm/blob/master/rust_fsm_dsl/src/lib.rs#L16).

**Comment by xkr47** [comment]
Thanks for your feedback!

As a level 4 Rust noob I'll have to learn about associated constants first :) Also, how would such a constant be used? While the program is running?

Yeah maybe leave it up to the user at least for now.

Regarding configurable (which I agree on); did you mean using annotations or DSL syntax extensions or something else?

**Comment by eugene-babichenko** [comment]
> Also, how would such a constant be used? While the program is running?

You'll have a trait like that:

```rust
trait StateMachine {
    const DOT: &'static str;
    /// ...
}
```

The constant `DOT` is generated for each type implementing this trait, for example:

```rust
impl StateMachine for A {
    const DOT: &'static str = "...";
}
```

This constant can then be used by users of type `A` like this: `A::DOT`.

So yeah, you can get the value of this constant during the program run or, for example, use it in some `const` expression that will be evaluated during the compilation process.

> Regarding configurable (which I agree on); did you mean using annotations or DSL syntax extensions or something else?

I was thinking of DSL syntax extensions, for example, something like this (just an example, you may think of a more suitable syntax):

```rust
state_machine! {
    dot_config {
        Init [shape=circle],
        State [shape=square],
        Transition [color=green],
    }
}
```

**Comment by xkr47** [comment]
> So yeah, you can get the value of this constant during the program run or, for example, use it in some const expression that will be evaluated during the compilation process.

How can this be achieved? Sorry for not knowing the whole build process very well yet.. :)

Also, thanks for the great ideas! I'll see what/when I can do! Working on fine-tuning the rendering of my state diagram, it gets quite messy quite fast with 10 states and 6..14 transitions form each :)

**Comment by eugene-babichenko** [comment]
Basically all you need to do now is to incorporate your code into the function implementing `state_machine` machine macro, that's it. Once it is generated it can then be accessed by the user.

**Comment by xkr47** [comment]
I mean how can you access/extract the generated statemachine dot graph from e.g. build tools if it exists as an associated constant string?

**Comment by eugene-babichenko** [comment]
Well, that's a good question. AFAIK one cannot modify the documentation string during the compilation time,

**Comment by eugene-babichenko** [comment]
I closed #4 because there was no updates on it. For anyone reading this: please refer to [this comment](https://github.com/eugene-babichenko/rust-fsm/pull/4#pullrequestreview-550703795) before doing the same  thing.

The idea described in this issue is not bad though, so contributions are welcome.

**Comment by eugene-babichenko** [comment]
Another approach to this might be outputting a `.dot` file somewhere under `target/` in the build time and being able to change the output location via some environment variable.

**Comment by eugene-babichenko** [comment]
This commit is kinda related, but it uses Mermaid instead. If you still want to use dot and output dot files, this commit provides a good general framework for such things within the current architecture. https://github.com/eugene-babichenko/rust-fsm/commit/f97d785e7a45dc8ed42246e810ad6b3336a8ea81
